PWW\DataFactoryBundle\Entity\Users:
    type: entity
    table: users
    uniqueConstraints:
        username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: text
            nullable: true
            length: null
            fixed: false
        friendlyname:
            type: text
            nullable: true
            length: null
            fixed: false
    lifecycleCallbacks: {  }
